package bytebazaar;

import java.util.LinkedList;

public class BuyerLedger {
    private LinkedList<Buyer> buyerLedger; //list of buyers,but not the complete list
    private Buyer currentBuyer; //reference to current buyer will be stored when logged in

    public BuyerLedger() {
        buyerLedger= new LinkedList<Buyer>();
    }

    //This fucntion creates new buyer(Default) and returns the newly assigned UserID 
    // which is autogenerated by DB (using identity)
    //Note: -1 means failed to save, -2 means sql exception occurred
    public int createUser(String name, String email, String phone, String password) {
        if (DBHandler.getInstance().checkUserExists(email) == false ) {
            Buyer b= new Buyer(email, password, phone, name);
            
            int returnID = DBHandler.getInstance().save(b);
            if(returnID>0) { //no error occurred; 
                b.setID(returnID);
                this.buyerLedger.add(b); //save to buyer ledger ,for quick reference, as most will login after signup.
            }
            return returnID;
        } else {
            //An acc already exists with this email
            return -1;
        }
    }

    public boolean loginRequest(String email, String password, String userType) {
        //TODO Check in ledger to authenticate email if user already there
        Buyer b = DBHandler.getInstance().authenticateLogin(email, password, userType);
        if(b!=null) {
            currentBuyer=b;
            currentBuyer.setDetails();
            return true;
        } else {
            System.out.println("authenticate login returned null");
            return false;
        }

    }
}
